#!/usr/bin/python3

import sys
from Common import *
import AnsibleDriver

def process_command(command, args):
  match command:
    case "list":
      AnsibleDriver.list_instances(args)
    case "deploy":
      print("deploy")
    case "change-type":
      AnsibleDriver.change_instance_type(args)
    case "register":
      print("register")
    case "deregister":
      print("deregister")
    case "upload":
      AnsibleDriver.upload_to_hosts(args)
    case default:
      print("Default")

if len(sys.argv) < 2:
  print("Usage: %s [command] {args...}" % sys.argv[0])
  exit(-1)

command = sys.argv[1]
args = sys.argv[2:]


process_command(command, args)

