#- hosts: "{{ target_host }}"
- hosts: localhost
  connection: local

  tasks:
    - name: Gather info. of target instances
      ec2_instance_info:
        region: us-west-2
        filters:
          '{ "tag:{{ tag_key }}": "{{ tag_value }}" }'
      register: targets

    - name: Stop target instances
      ec2_instance:
        state: stopped
        filters:
          '{ "tag:{{ tag_key }}": "{{ tag_value }}" }'
        wait: yes

    - name: Change instance type of target hosts
#      ec2_instance:
#        filters:
#          '{ "tag:{{ tag_key }}": "{{ tag_value }}" }'
#        instance_type: "{{ target_type }}"
#        wait: yes
      shell:
        cmd: aws ec2 modify-instance-attribute --instance-type="{{ target_type }}" --instance-id="{{ item.instance_id }}"
      no_log: true
      loop: "{{ targets.instances }}"

    - name: Booting modified instances
      ec2_instance:
        state: running
        filters:
          '{ "tag:{{ tag_key }}": "{{ tag_value }}" }'
        wait: yes
