- hosts: localhost
  connection: local

  vars:
    lb_arn: "arn:aws:elasticloadbalancing:us-west-2:423287729285:loadbalancer/app/web-lb-01/ed85fd0754b9ef46"
    service_port: "8000"

  tasks:
    - name: Gather info. of target instances
      ec2_instance_info:
        region: us-west-2
        filters:
          '{ "tag:{{ tag_key }}": "{{ tag_value }}" }'
      register: targets

    - name: Remove target hosts from target group of load balancer
      elb_target:
        target_group_name: "{{ target_group_name }}"
        target_id: "{{ item.instance_id }}"
        target_port: "{{ service_port }}"
        state: absent
      loop: "{{ targets.instances }}"
      no_log: true

